import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const { PGlite } = await import(process.env.PGLITE_IMPORT ?? '@electric-sql/pglite');
const db = new PGlite();
await db.exec('create role anon; create role authenticated; create role service_role bypassrls;');
await db.exec(await readFile(new URL('../migrations/20260906054107_btc_research_demo.sql', import.meta.url), 'utf8'));
const run='test-btc-research';const h='a'.repeat(64),f='b'.repeat(64),e='c'.repeat(64);
await db.query('insert into btc_demo_runs(run_id,bundle_id,bundle_sha256,feature_contract_sha256,execution_contract_sha256,manifest) values($1,$1,$2,$3,$4,$5)',[run,h,f,e,{}]);
const at='2026-07-17T00:00:00.000Z',next='2026-07-17T00:15:00.000Z';
const initial={schema_version:1,run_id:run,bundle_id:run,bundle_sha256:h,version:1,last_open_ts:at,started_at:at,initial_open:100,initial_equity:1,display_capital:10000,cash:0,units:.01,benchmark_units:.01,fees:0,borrow:0,trades:0,turnover:0,pending_target:null,pending_decision_ts:null,pending_due_at:null,last_mark_ts:null,last_mark_price:null,equity:1,benchmark_equity:1,peak_equity:1,benchmark_peak_equity:1,max_drawdown:0,benchmark_max_drawdown:0,current_open_equity:1,current_open_exposure:1};
const envelope=(state,expected,event=state.last_open_ts)=>({ok:true,run_id:run,bundle_id:run,bundle_sha256:h,feature_contract_sha256:f,execution_contract_sha256:e,event_ts:event,expected_state_version:expected,state,snapshots:[],forecast:null,events:[],data:{timely:true}});
const call=async p=>(await db.query('select record_btc_demo_transition($1::jsonb) as result',[p])).rows[0].result;
let tests=0;
async function rejects(p,pattern){await assert.rejects(()=>call(p),pattern);tests++;}
await db.exec('set role service_role');
await rejects({...envelope(initial,0),bundle_sha256:'d'.repeat(64)},/contract mismatch/);
assert.equal((await call(envelope(initial,0))).status,'applied');tests++;
assert.equal((await call(envelope(initial,0))).status,'already_processed');tests++;
assert.equal((await db.query('select version from btc_demo_state')).rows[0].version,1);tests++;
const marked={...initial,version:2,last_open_ts:next,last_mark_ts:at,last_mark_price:102,equity:1.02,benchmark_equity:1.02,peak_equity:1.02,benchmark_peak_equity:1.02,current_open_equity:1.03};
const snapshot={timestamp:at,price:102,equity:1.02,benchmark_equity:1.02,exposure:1,cash:0,units:.01,fees:0,borrow:0,turnover:0,trades:0,max_drawdown:0,benchmark_max_drawdown:0};
const transition={...envelope(marked,1),snapshots:[snapshot]};
await rejects({...transition,expected_state_version:0,state:{...marked,version:1}},/version conflict/);
await rejects({...transition,state:{...marked,initial_open:99}},/endowment changed/);
await rejects({...transition,snapshots:[{...snapshot,timestamp:next}]},/chronology/);
await rejects({...transition,snapshots:[{...snapshot,equity:-1}]},/check constraint/);
await rejects({...transition,state:{...marked,last_mark_ts:null}},/state mark/);
await rejects({...transition,state:{...marked,pending_target:1.1,pending_decision_ts:next,pending_due_at:next}},/pending intent/);
await rejects({...transition,state:{...marked,units:'NaN'}},/invalid BTC state/);
await rejects({...transition,state:{...marked,pending_due_at:next}},/empty intent/);
await rejects({...transition,state:{...marked,trades:1.5}},/trade count/);
await rejects({...transition,state:{...marked,current_open_equity:null}},/jointly available/);
await rejects({...transition,snapshots:undefined},/envelope/);
await rejects({...transition,forecast:{decision_ts:next,available:false,action_eligible:false,mu:null,variance:null,target:null}},/six-hour clock/);
assert.equal((await db.query('select count(*)::int n from btc_demo_snapshots')).rows[0].n,0);tests++;
const malformed={...transition,events:[{event_id:'bad',timestamp:next,kind:'unsupported',details:{}}]};
await rejects(malformed,/check constraint/);
assert.equal((await db.query('select count(*)::int n from btc_demo_snapshots')).rows[0].n,0);tests++;
assert.equal((await db.query('select version from btc_demo_state')).rows[0].version,1);tests++;
assert.equal((await call(transition)).status,'applied');tests++;
assert.equal((await call(transition)).status,'already_processed');tests++;
assert.equal((await db.query('select count(*)::int n from btc_demo_snapshots')).rows[0].n,1);tests++;
const missingAt='2026-07-17T00:30:00.000Z';
assert.equal((await call(envelope({...marked,version:3,last_open_ts:missingAt,current_open_equity:null,current_open_exposure:null},2))).status,'applied');tests++;
await db.exec('reset role; set role anon');
assert.equal((await db.query('select count(*)::int n from btc_demo_state')).rows[0].n,1);tests++;
await assert.rejects(()=>call(transition),/permission denied/);tests++;
await assert.rejects(()=>db.query('delete from btc_demo_state'),/permission denied/);tests++;
await db.exec('reset role');
const grants=(await db.query("select has_function_privilege('anon','record_btc_demo_transition(jsonb)','EXECUTE') anon_exec, has_function_privilege('authenticated','record_btc_demo_transition(jsonb)','EXECUTE') auth_exec, has_function_privilege('service_role','record_btc_demo_transition(jsonb)','EXECUTE') server_exec")).rows[0];
assert.deepEqual(grants,{anon_exec:false,auth_exec:false,server_exec:true});tests++;
assert.equal((await db.query("select count(*)::int n from pg_class where relname like 'btc_demo_%' and relkind='r' and relrowsecurity")).rows[0].n,5);tests++;
console.log(JSON.stringify({status:'pass',tests,engine:'PGlite PostgreSQL',scope:'real migration and PL/pgSQL transaction/idempotency/CAS/rollback/RLS grants, in-memory only'}));
await db.close();
